export const FETCH_USER = 'FETCH_USER'
export const UNSET_USER = 'UNSET_USER'
export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const SET_SUCCESS_MESSAGE = 'SUCCESS_MESSAGE'
export const UNSET_SUCCESS_MESSAGE = 'UNSET_SUCCESS_MESSAGE'
